### ISSUE TITLE
Java Api client

### ISSUE THREAD

**Issue by GuillermoBlasco** [zalando/shop-api-documentation#5]
Dear Zalando folks,

We, at Stilavia, have developed as a little prototype project of a Java client for your shop api. Check it out here https://github.com/Stilavia/zalando-api. We expect to make it grow and use it later as an experimental feature.

We think that since you opened that api to the world we could open our client also to the world :)

The issue is: Do you want to link from your documentation our Java client?

Best regards

**Comment by benjaminwagner** [comment]
Thanks for making this public. I like how it looks so far. I think its no problem to link it from our documentation, maybe we just wait until you finished your first version (e.g. not 1.0.0-SNAPSHOT and Article model implemented).

just some things I found when looking at the code:
- There is a typo in the locale of ZalandoApi.Domain.da_DK, it should be "da-DK".
- You should remove ZalandoApiBuilder.enableHttps() because the api is only reachable by https
- Please consider to always use or at least add the option to enable gzip compression. The API supports content encoding and transfer encoding compression.

**Comment by jukey** [comment]
Hi @GuillermoBlasco,

The client is now listed our documentation as [unofficial 3rd party client](https://github.com/zalando/shop-api-documentation/wiki/Zalando-Shop-API-3rd-party-clients). There is also a [google group](https://groups.google.com/forum/#!forum/zalando-api) now for developers and users of the Zalando Shop API. Feel kindly invited to subscribe to this group in order to keep up to date regarding API changes.

Kind regards Uwe
